"""Stage 2 core cricket schema.

Revision ID: 20260908_0002
Revises: 20260903_0001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "20260908_0002"
down_revision: str | None = "20260903_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(
        *values,
        name=name,
        create_type=False,
    )


def upgrade() -> None:
    bind = op.get_bind()

    enum_types = (
        _enum("team_status", "active", "archived"),
        _enum(
            "player_status",
            "active",
            "inactive",
            "archived",
        ),
        _enum("venue_status", "active", "archived"),
        _enum(
            "tournament_status",
            "draft",
            "active",
            "completed",
            "archived",
        ),
        _enum(
            "match_type",
            "t20",
            "odi",
            "test",
            "other",
        ),
        _enum(
            "match_status",
            "draft",
            "ready",
            "live",
            "innings_break",
            "completed",
            "abandoned",
        ),
        _enum("toss_decision", "bat", "bowl"),
        _enum(
            "player_role",
            "batter",
            "bowler",
            "all_rounder",
            "wicket_keeper",
        ),
        _enum(
            "innings_status",
            "pending",
            "live",
            "break",
            "completed",
        ),
        _enum(
            "delivery_status",
            "recorded",
            "void",
        ),
        _enum(
            "correction_type",
            "void",
            "amendment",
        ),
        _enum(
            "audit_action",
            "created",
            "updated",
            "archived",
            "restored",
            "corrected",
        ),
    )

    for enum_type in enum_types:
        enum_type.create(bind, checkfirst=True)

    op.create_table(
        "teams",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "short_name",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "country",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "status",
            _enum("team_status", "active", "archived"),
            nullable=False,
            server_default=sa.text("'active'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name="team_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(short_name)) > 0",
            name="team_short_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(code)) > 0",
            name="team_code_not_blank",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_teams",
        ),
        sa.UniqueConstraint(
            "code",
            name="uq_teams_code",
        ),
        sa.UniqueConstraint(
            "name",
            name="uq_teams_name",
        ),
    )

    op.create_index(
        "ix_teams_status",
        "teams",
        ["status"],
    )
    op.create_index(
        "ix_teams_name",
        "teams",
        ["name"],
    )

    op.create_table(
        "players",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "full_name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "short_name",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "date_of_birth",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "nationality",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "external_id",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "status",
            _enum(
                "player_status",
                "active",
                "inactive",
                "archived",
            ),
            nullable=False,
            server_default=sa.text("'active'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "length(trim(full_name)) > 0",
            name="player_full_name_not_blank",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_players",
        ),
        sa.UniqueConstraint(
            "external_id",
            name="uq_players_external_id",
        ),
        sa.UniqueConstraint(
            "full_name",
            "date_of_birth",
            name="uq_players_full_name_date_of_birth",
        ),
    )

    op.create_index(
        "ix_players_status",
        "players",
        ["status"],
    )
    op.create_index(
        "ix_players_full_name",
        "players",
        ["full_name"],
    )

    op.create_table(
        "venues",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "city",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "country",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "address",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "capacity",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "status",
            _enum(
                "venue_status",
                "active",
                "archived",
            ),
            nullable=False,
            server_default=sa.text("'active'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name="venue_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(city)) > 0",
            name="venue_city_not_blank",
        ),
        sa.CheckConstraint(
            "capacity IS NULL OR capacity >= 0",
            name="venue_capacity_non_negative",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_venues",
        ),
        sa.UniqueConstraint(
            "name",
            "city",
            name="uq_venues_name_city",
        ),
    )

    op.create_index(
        "ix_venues_status",
        "venues",
        ["status"],
    )
    op.create_index(
        "ix_venues_name",
        "venues",
        ["name"],
    )
    op.create_index(
        "ix_venues_city",
        "venues",
        ["city"],
    )

    op.create_table(
        "tournaments",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "slug",
            sa.String(length=180),
            nullable=False,
        ),
        sa.Column(
            "season",
            sa.String(length=40),
            nullable=True,
        ),
        sa.Column(
            "organizer",
            sa.String(length=160),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "start_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "end_date",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "status",
            _enum(
                "tournament_status",
                "draft",
                "active",
                "completed",
                "archived",
            ),
            nullable=False,
            server_default=sa.text("'draft'"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0",
            name="tournament_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(slug)) > 0",
            name="tournament_slug_not_blank",
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name="tournaments_dates_valid",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_tournaments",
        ),
        sa.UniqueConstraint(
            "slug",
            name="uq_tournaments_slug",
        ),
        sa.UniqueConstraint(
            "name",
            "season",
            name="uq_tournaments_name_season",
        ),
    )

    op.create_index(
        "ix_tournaments_status",
        "tournaments",
        ["status"],
    )
    op.create_index(
        "ix_tournaments_name",
        "tournaments",
        ["name"],
    )
    op.create_index(
        "ix_tournaments_season",
        "tournaments",
        ["season"],
    )

    op.create_table(
        "matches",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=180),
            nullable=True,
        ),
        sa.Column(
            "match_number",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "team_a_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "team_b_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tournament_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "venue_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "match_type",
            _enum(
                "match_type",
                "t20",
                "odi",
                "test",
                "other",
            ),
            nullable=False,
            server_default=sa.text("'t20'"),
        ),
        sa.Column(
            "total_overs",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            _enum(
                "match_status",
                "draft",
                "ready",
                "live",
                "innings_break",
                "completed",
                "abandoned",
            ),
            nullable=False,
            server_default=sa.text("'draft'"),
        ),
        sa.Column(
            "toss_winner_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "toss_decision",
            _enum(
                "toss_decision",
                "bat",
                "bowl",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "team_a_id <> team_b_id",
            name="matches_teams_must_differ",
        ),
        sa.CheckConstraint(
            "total_overs > 0",
            name="matches_total_overs_positive",
        ),
        sa.CheckConstraint(
            "match_number IS NULL OR match_number > 0",
            name="matches_match_number_positive",
        ),
        sa.CheckConstraint(
            "(toss_winner_id IS NULL AND toss_decision IS NULL) OR "
            "(toss_winner_id IS NOT NULL AND toss_decision IS NOT NULL)",
            name="matches_toss_fields_together",
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["teams.id"],
            name="fk_matches_team_a_id_teams",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["teams.id"],
            name="fk_matches_team_b_id_teams",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
            name="fk_matches_tournament_id_tournaments",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
            name="fk_matches_venue_id_venues",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["toss_winner_id"],
            ["teams.id"],
            name="fk_matches_toss_winner_id_teams",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_matches",
        ),
    )

    op.create_index(
        "ix_matches_status",
        "matches",
        ["status"],
    )
    op.create_index(
        "ix_matches_scheduled_at",
        "matches",
        ["scheduled_at"],
    )
    op.create_index(
        "ix_matches_team_a_id",
        "matches",
        ["team_a_id"],
    )
    op.create_index(
        "ix_matches_team_b_id",
        "matches",
        ["team_b_id"],
    )

    op.create_table(
        "team_players",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "team_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "player_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "role",
            _enum(
                "player_role",
                "batter",
                "bowler",
                "all_rounder",
                "wicket_keeper",
            ),
            nullable=False,
            server_default=sa.text("'batter'"),
        ),
        sa.Column(
            "squad_number",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "joined_on",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "left_on",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "squad_number IS NULL OR squad_number > 0",
            name="team_players_squad_number_positive",
        ),
        sa.CheckConstraint(
            "left_on IS NULL OR joined_on IS NULL OR left_on >= joined_on",
            name="team_players_dates_valid",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_team_players_team_id_teams",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name="fk_team_players_player_id_players",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_team_players",
        ),
        sa.UniqueConstraint(
            "team_id",
            "player_id",
            name="uq_team_players_team_player",
        ),
    )

    op.create_index(
        "ix_team_players_team_id",
        "team_players",
        ["team_id"],
    )
    op.create_index(
        "ix_team_players_player_id",
        "team_players",
        ["player_id"],
    )

    op.create_table(
        "match_players",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "match_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "team_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "player_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "batting_order",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "role",
            _enum(
                "player_role",
                "batter",
                "bowler",
                "all_rounder",
                "wicket_keeper",
            ),
            nullable=False,
            server_default=sa.text("'batter'"),
        ),
        sa.Column(
            "is_captain",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "is_wicket_keeper",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "batting_order IS NULL OR batting_order > 0",
            name="match_players_batting_order_positive",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name="fk_match_players_match_id_matches",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_match_players_team_id_teams",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name="fk_match_players_player_id_players",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_match_players",
        ),
        sa.UniqueConstraint(
            "match_id",
            "player_id",
            name="uq_match_players_match_player",
        ),
        sa.UniqueConstraint(
            "match_id",
            "team_id",
            "batting_order",
            name="uq_match_players_batting_order",
        ),
    )

    op.create_index(
        "ix_match_players_match_id",
        "match_players",
        ["match_id"],
    )
    op.create_index(
        "ix_match_players_team_id",
        "match_players",
        ["team_id"],
    )
    op.create_index(
        "ix_match_players_player_id",
        "match_players",
        ["player_id"],
    )

    op.create_table(
        "innings",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "match_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "innings_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "batting_team_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "bowling_team_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            _enum(
                "innings_status",
                "pending",
                "live",
                "break",
                "completed",
            ),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column(
            "total_runs",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "wickets",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "legal_balls",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "striker_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "non_striker_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "current_bowler_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "innings_number > 0",
            name="innings_number_positive",
        ),
        sa.CheckConstraint(
            "batting_team_id <> bowling_team_id",
            name="innings_teams_must_differ",
        ),
        sa.CheckConstraint(
            "total_runs >= 0",
            name="innings_total_runs_non_negative",
        ),
        sa.CheckConstraint(
            "wickets >= 0",
            name="innings_wickets_non_negative",
        ),
        sa.CheckConstraint(
            "legal_balls >= 0",
            name="innings_legal_balls_non_negative",
        ),
        sa.CheckConstraint(
            "striker_id IS NULL OR non_striker_id IS NULL OR striker_id <> non_striker_id",
            name="innings_batters_must_differ",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            name="fk_innings_match_id_matches",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["batting_team_id"],
            ["teams.id"],
            name="fk_innings_batting_team_id_teams",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bowling_team_id"],
            ["teams.id"],
            name="fk_innings_bowling_team_id_teams",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["striker_id"],
            ["players.id"],
            name="fk_innings_striker_id_players",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["non_striker_id"],
            ["players.id"],
            name="fk_innings_non_striker_id_players",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_bowler_id"],
            ["players.id"],
            name="fk_innings_current_bowler_id_players",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_innings",
        ),
        sa.UniqueConstraint(
            "match_id",
            "innings_number",
            name="uq_innings_match_number",
        ),
    )

    op.create_index(
        "ix_innings_match_id",
        "innings",
        ["match_id"],
    )
    op.create_index(
        "ix_innings_status",
        "innings",
        ["status"],
    )

    op.create_table(
        "deliveries",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "innings_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "delivery_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "over_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "ball_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "striker_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "non_striker_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "bowler_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "batter_runs",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "extra_runs",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_runs",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "is_legal_ball",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "status",
            _enum(
                "delivery_status",
                "recorded",
                "void",
            ),
            nullable=False,
            server_default=sa.text("'recorded'"),
        ),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "delivery_number > 0",
            name="deliveries_delivery_number_positive",
        ),
        sa.CheckConstraint(
            "over_number > 0",
            name="deliveries_over_number_positive",
        ),
        sa.CheckConstraint(
            "ball_number > 0",
            name="deliveries_ball_number_positive",
        ),
        sa.CheckConstraint(
            "batter_runs >= 0 AND extra_runs >= 0 AND total_runs >= 0",
            name="deliveries_runs_non_negative",
        ),
        sa.CheckConstraint(
            "total_runs = batter_runs + extra_runs",
            name="deliveries_total_runs_match_components",
        ),
        sa.CheckConstraint(
            "striker_id <> non_striker_id",
            name="deliveries_batters_must_differ",
        ),
        sa.ForeignKeyConstraint(
            ["innings_id"],
            ["innings.id"],
            name="fk_deliveries_innings_id_innings",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["striker_id"],
            ["players.id"],
            name="fk_deliveries_striker_id_players",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["non_striker_id"],
            ["players.id"],
            name="fk_deliveries_non_striker_id_players",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bowler_id"],
            ["players.id"],
            name="fk_deliveries_bowler_id_players",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_deliveries",
        ),
        sa.UniqueConstraint(
            "innings_id",
            "delivery_number",
            name="uq_deliveries_innings_delivery_number",
        ),
    )

    op.create_index(
        "ix_deliveries_innings_id",
        "deliveries",
        ["innings_id"],
    )
    op.create_index(
        "ix_deliveries_innings_status",
        "deliveries",
        ["innings_id", "status"],
    )

    op.create_table(
        "delivery_corrections",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "delivery_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "correction_type",
            _enum(
                "correction_type",
                "void",
                "amendment",
            ),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(trim(reason)) > 0",
            name="delivery_corrections_reason_not_blank",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name="fk_delivery_corrections_delivery_id_deliveries",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_delivery_corrections",
        ),
    )

    op.create_index(
        "ix_delivery_corrections_delivery_id",
        "delivery_corrections",
        ["delivery_id"],
    )

    op.create_table(
        "audit_logs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "entity_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "action",
            _enum(
                "audit_action",
                "created",
                "updated",
                "archived",
                "restored",
                "corrected",
            ),
            nullable=False,
        ),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "length(trim(entity_type)) > 0",
            name="audit_logs_entity_type_not_blank",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_audit_logs",
        ),
    )

    op.create_index(
        "ix_audit_logs_entity",
        "audit_logs",
        ["entity_type", "entity_id"],
    )
    op.create_index(
        "ix_audit_logs_actor_id",
        "audit_logs",
        ["actor_id"],
    )
    op.create_index(
        "ix_audit_logs_created_at",
        "audit_logs",
        ["created_at"],
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_table("audit_logs")
    op.drop_table("delivery_corrections")
    op.drop_table("deliveries")
    op.drop_table("innings")
    op.drop_table("match_players")
    op.drop_table("team_players")
    op.drop_table("matches")
    op.drop_table("tournaments")
    op.drop_table("venues")
    op.drop_table("players")
    op.drop_table("teams")

    enum_types = (
        _enum(
            "audit_action",
            "created",
            "updated",
            "archived",
            "restored",
            "corrected",
        ),
        _enum(
            "correction_type",
            "void",
            "amendment",
        ),
        _enum(
            "delivery_status",
            "recorded",
            "void",
        ),
        _enum(
            "innings_status",
            "pending",
            "live",
            "break",
            "completed",
        ),
        _enum(
            "player_role",
            "batter",
            "bowler",
            "all_rounder",
            "wicket_keeper",
        ),
        _enum(
            "toss_decision",
            "bat",
            "bowl",
        ),
        _enum(
            "match_status",
            "draft",
            "ready",
            "live",
            "innings_break",
            "completed",
            "abandoned",
        ),
        _enum(
            "match_type",
            "t20",
            "odi",
            "test",
            "other",
        ),
        _enum(
            "tournament_status",
            "draft",
            "active",
            "completed",
            "archived",
        ),
        _enum(
            "venue_status",
            "active",
            "archived",
        ),
        _enum(
            "player_status",
            "active",
            "inactive",
            "archived",
        ),
        _enum(
            "team_status",
            "active",
            "archived",
        ),
    )

    for enum_type in enum_types:
        enum_type.drop(
            bind,
            checkfirst=True,
        )